[package]
name = "discord-record"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.13.1"
itertools = "0.10.5"
serenity = { version = "0.11.5", default_features = false, features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "voice"] }
songbird = "0.3.1"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "sync", "fs"] }
